name: CI

on:
  push:

jobs:
  deploy:
    permissions:
      contents: read
      packages: write

    uses: IIS-Design/.github/.github/workflows/container-deploy.yml@main

    with:
      app: uxipsos-pages
      container-port: 80
      smoke-path: /uxipsos-pages/_health
